---
tags: [messaging, rabbitmq]
projects: [spring-amqp]
---
:spring_boot_version: 1.1.4.RELEASE
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-rpc-rabbitmq
This guide walks you through the process of setting up a RabbitMQ AMQP server and clinet for RPC calls.

== What you'll build

You'll build an  server application and a client application that calls the server using Spring AMQP's `RabbitTemplate`.

== What you'll need
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]
+
- RabbitMQ server (installation instructions below)

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


[[scratch]]
== Set up the project

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_system_intro.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/create_directory_structure_hello.adoc[]


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/create_both_builds.adoc[]

`build.gradle`
// AsciiDoc source formatting doesn't support groovy, so using java instead
[source,java]
----
include::initial/build.gradle[]
----

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/spring-boot-gradle-plugin.adoc[]


Before you can build your messaging application, you need to set up the server that will handle receiving and sending messages.

RabbitMQ is an AMQP server. The server is freely available at http://www.rabbitmq.com/download.html. You can download it manually, or if you are using a Mac with homebrew:

----
brew install rabbitmq
----

Unpack the server and launch it with default settings.

----
rabbitmq-server
----

You should see something like this:

....
            RabbitMQ 3.1.3. Copyright (C) 2007-2013 VMware, Inc.
##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
##  ##
##########  Logs: /usr/local/var/log/rabbitmq/rabbit@localhost.log
######  ##        /usr/local/var/log/rabbitmq/rabbit@localhost-sasl.log
##########
            Starting broker... completed with 6 plugins.
....

[[initial]]
== Create a service
`src/main/java/hello/CalculationService.java`
[source,java]
----
include::complete/src/main/java/hello/CalculationService.java[]
----

== Create the service implementation
`src/main/java/hello/CalculationServiceImpl.java`
[source,java]
----
include::complete/src/main/java/hello/CalculationServiceImpl.java[]
----

== Create a RabbitMQ RPC server application
`src/main/java/hello/ServerApplication.java`
[source,java]
----
include::complete/src/main/java/hello/ServerApplication.java[]
----

== Create a RabbitMQ RPC client application
`src/main/java/hello/ClientApplication.java`
[source,java]
----
include::complete/src/main/java/hello/ClientApplication.java[]
----


== Create a RabbitMQ RPC client 
`src/main/java/hello/Client.java`
[source,java]
----
include::complete/src/main/java/hello/Client.java[]
----


Run the server application, than run the client application.
You should see output like this:

	91 + 96 =187.0
	78 + 21 =99.0
	60 * 59 =3540.0
	91 + 49 =140.0
	16 + 70 =86.0
	34 * 91 =3094.0
	32 + 97 =129.0

== Summary
Congratulations! You've just developed a simple RPC server and client application with Spring and RabbitMQ. There's http://docs.spring.io/spring-amqp/reference/html/quick-tour.html[more you can do with Spring and RabbitMQ] than what is covered here, but this should provide a good start.

